dns-updater-password: ENC[AES256_GCM,data:xz/YwCLAOP5EG4SYGBk22uVy8ErdNxhjXfcPlgKqhb/VHu7tJtQ00w==,iv:DaAIRWqqaA1p9qvB0tyMW5nCIwnzkF6zleIQGfBBkOI=,tag:OhRdiHQ3AYIPWQewEJ3Njg==,type:str]
dns-updater-zone-id: ENC[AES256_GCM,data:X9s6qsJ8oCsfQNKkMvgVYCzehT0E9DaEq42cIwp3cLQ=,iv:76tKojlh2PGUmGDu8+xdC0xpWff5sqlyF9/DDYGwGd4=,tag:ncn3l8FJGyV7xx/HIHZNvw==,type:str]
sops:
    age:
        - recipient: age14jd2uvg5fwc2r2vgp4tsw5dy9rpksel97um2v494ws4tptult9ys50cndr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUWNUYThwNGd1dkRWU3lE
            YTV6SzZmczcvNkEwTlJnUGFEWHhTVURMK1JJClorOUdPb05YbDY2Kyt1Y25aTUlm
            eWNJSklwUDVLNWI5RGM0bktWRXgvdXcKLS0tIEdJWEhWVjFFUlNmVjBSZmpBaTY2
            ajAzMk5lRkZPT2xGaHZoSFZFOU9wYmcKtdZ06mzDtb5GtRfRNpTN3vT+FxQB0NKq
            j0gMO/Pgdc2T1pyk8wXYdR/XUt+GwLAYqFd2bOEyRxs3e/Crti2a4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T14:59:13Z"
    mac: ENC[AES256_GCM,data:30jgErNcmwvuG5kaEL4tR6p2eieSCeLRtML99tz3TM2BZX94WxwLXJNSb7j/YYGJAYMEcoF1WaYyGBdIQsNC+qE7JRMwUhkVpGsf06bp6AMuBMN/JKWHvtaUuFwcGHQvURwj1uzmPxXlIgh1ofc2tR8rKAE/aFprZ0E4Ba/TL1g=,iv:N0zjDhf3mKUaNFRWEdxmqpXYkmeFEJlYWO9ZFpSmnqs=,tag:xB8v32D65/nOV9BPXpw37w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
