grafana-oauth-client-id: ENC[AES256_GCM,data:h7osAKn4wJcIUjwodC17tvP+YuU7SyEZyFiMGsn1vUFgYVy1Lxzg1Q==,iv:mpKpHSgdV9eUKrgUFTtWbM4Urq4brbiUjzlysIB6jo8=,tag:IT09QUrVohpQh30a4uK8+Q==,type:str]
grafana-oauth-client-secret: ENC[AES256_GCM,data:jBUjCfjpLfrGsUn+G/41QQiI7tN8NHgRP/iMvR7Fx9LcFPlMIAmcK9RPUFIk17zTbpuzzRTqo4bjaBZUmCBbic2TYq7MvfKrTRy5/0QkXw+2jARvHVKIp72dhWrr+WL6qq8RkEyiuKkKwLnnnmGgSCl4DP4jALs5MZxg+B6SN44=,iv:xobCl9kBgmjQxyGjGz1rYm/3N8dfyz8bKwZqWqOhwQ4=,tag:mSN9nHs09wCu9Z5Tn1VotQ==,type:str]
sops:
    age:
        - recipient: age14jd2uvg5fwc2r2vgp4tsw5dy9rpksel97um2v494ws4tptult9ys50cndr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbCt4NEhjdFN6QUR1RmxN
            U1lOQll6a1BRN1ppc3dnOWdNWTZDbGJlTXk0CmdyNm5MWVJZSTBxNTFISUVxWGFU
            c2ZKZEw0NDZlRzdHdmdhSU9NaFBJdzQKLS0tIFJ3Z2hFRnBEdmlvbkRUN3g5Tnlo
            aFl5MTdTd2V5ZGlpK0tLM1ZpRU5BaEUK7g0oFAptb+IZKjMggGQnEVU2ZGBaGrxW
            1hoG6g0r5YqaUBqaRC763V8qaTqWfNZ2PXYrJDxCv8Opxz0wuUQgxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T18:19:38Z"
    mac: ENC[AES256_GCM,data:pvx20yuu51QTXKXlvP4DrAj9RBMAd4/BF4H9JyHUJ/Uyn+sDCQgi5F110mIe/nuGQR68z+Z3IXFUd+uwXnN0mVDtfqUwaRXYvs1H0YBcLMxTNOzoPBs4jLHQlbXZOE08gD3/ZgryAHd0DUq7fgzegeKnZqRNOeB8owmzkQ44ZQw=,iv:aifT2cn4UjiB3OXuC+y7krhK1btt7QOpUq9ATsdPmic=,tag:sixIe1ZGjvZUE1XoWvF8Ig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
